replicaCount: 1

image:
  repository: 033545909213.dkr.ecr.ap-northeast-2.amazonaws.com/riskope
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: alb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: riskope-dev.xgram.cleavework.com
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:033545909213:certificate/925d3a68-ba42-4173-88da-ee007c16ffcd
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  hosts:
    - host: riskope-dev.xgram.cleavework.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 250m
    memory: 2048Mi

livenessProbe:
  httpGet:
    path: /api/v1/health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

nodeSelector:
  node-pool: dagster-runner-node-pool
tolerations: []
affinity: {}

aws:
  region: "ap-northeast-2"

externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
    create: false
  target:
    name: ""
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: riskope/env

env: {}

extraEnv: []
extraEnvFrom: []
